### ISSUE TITLE
Remove secrets from repo

### ISSUE THREAD

**Issue by rwd** [europeana/europeana-statistics-dashboard#1]
**This public repo contains secrets** in the following files:
- config/database.yml
- config/secrets.yml
- config/newrelic.yml
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb

These need to be removed from the repo, and no longer considered secret. Any API keys should be invalidated and regenerated.

Configuration files should assign per-environment secrets from environment variables.

**Comment by rwd** [comment]
@amitbadheka please note and acknowledge this issue.

You will need to take action to secure the various accounts with their secrets made public by having been committed to this repo, and adjust the configuration files to read secrets from environment variables.

**Comment by amitkbadheka** [comment]
@rwd I will see to it and work on the same.

**Comment by rwd** [comment]
@amitbadheka can you confirm that the [API keys](https://github.com/europeana/europeana-statistics-dashboard/tree/fd988ceaff84f3b4baa6e5a48e1b9eca89d61a36/config) previously committed to this repo have been invalidated?

**Comment by amitkbadheka** [comment]
@rwd, yes. I have done the same.
