### ISSUE TITLE
Add password confirmation field to account security form

### ISSUE THREAD

**Issue by rwd** [europeana/europeana-statistics-dashboard#6]
As shown in the screenshot below, there is no password confirmation field on the account security form, making it very easy for a user to change their password to something they did not intend.

It is standard practice to include a password confirmation field on such forms.

![screenshot_2015-10-22_10-00-13](https://cloud.githubusercontent.com/assets/218337/10661090/c11a448c-78a3-11e5-8a47-c83c5f592c5b.png)

**Comment by amitkbadheka** [comment]
Added confirmation field for password
