### ISSUE TITLE
Lock gem dependencies

### ISSUE THREAD

**Issue by rwd** [europeana/europeana-statistics-dashboard#8]
Two gems in the bundle are sourced from Github without reference locks: best_in_place and simple_form.

As both of these are available on rubygems.org, it would be preferable to source them from there, unless there is a known need to use a more recent version from Github, in which case they should be locked by branch, tag or commit reference.

**Comment by amitkbadheka** [comment]
Removed the gem lock dependencies. Now the sources is rubygems.org
